### ISSUE TITLE
Why didn't you compare SI-SNR and SDR?

### ISSUE THREAD

**Issue by Fangbo0506** [Sanyuan-Chen/CSS_with_Conformer#2]
I used the Conformer structure for single-channel separation, but the effect was not ideal.

**Comment by Sanyuan-Chen** [comment]
Hi, 

Did you use the pretrained Conformer model in README.md? You should be able to get the results as we reported in our paper if you download our released separation model and evaluate it on the LibriCSS dataset.

Since we evaluate our separation model on the LibriCSS dataset, which consists of real recordings of long-form multi-talker sessions, there are no true references for each unmixing speech but each transcription. So we use the same AM model for generating the estimated transcriptions of the separated speech of each model and compare the WER score of them.

**Comment by haoyz** [comment]
I'm also curious about its sound quality metrics. Did you test later? @Fangbo0506

**Comment by Fangbo0506** [comment]
Sorry，i don't do this work.Maybe you can test this&nbsp;quality metrics.






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Sanyuan-Chen/CSS_with_Conformer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月31日(星期四) 下午5:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Sanyuan-Chen/CSS_with_Conformer] Why didn't you compare SI-SNR and SDR? (#2)





 
I'm also curious about its sound quality metrics. Did you test later? @Fangbo0506
